POST http://localhost:4000/patients/add
Content-Type: application/json

{
  "name": "jhon doe",
  "email":"test@example.com",
  "address": "123 BEJA",
  "dateOfBirth": "1999-05-08",
  "registeredDate": "1999-05-08"
}